### ISSUE TITLE
Build using VS2022 Sln

### ISSUE THREAD

**Issue by GeorgeS2019** [svorwerk-dentsu/mediapipe-facial-analysis-toolkit#1]
### MediaPipe Solution (you are using)

FaceMesh with blendshape

### Programming language

c++/c#

### Are you willing to contribute it

None

### Describe the feature and the current behaviour/state

```shell
Blendshape
```

### Will this change the current API? How?

```shell
no
```

### Who will benefit with this feature?

Mocap communities

### Please specify the use cases for this feature

```shell
Mocap using Godot
```

### Any Other info

=> I know this is not your priority, hopefully the c++ dll you created, could be used for interop for c#

**Comment by GeorgeS2019** [comment]
I still stuck, not sure what is wrong. Any suggestion. 

So far, I only successful with a project that provides VS2022 Sln solutoin

```
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/xxx/_fffff/6b2dzj5r/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/xxx/_fffff/6b2dzj5r/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/xxx/_fffff/6b2dzj5r/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='Z://xxfolder//python.exe' is not executable. Is it the python binary?
```

**Comment by GeorgeS2019** [comment]
https://github.com/google/mediapipe/issues/4203

**Comment by GeorgeS2019** [comment]
https://github.com/andrechen/mediapipe/tree/master/visualstudio
